name: Unit Tests

on:
  pull_request:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements.txt pytest
    - name: Run tests
      run: pytest src/test_setup.py  # Adjust if tests are elsewhere
